name: Android CI/CD

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Version Code and Version Name
        run: |
          echo "VERSION_CODE=$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
          echo "VERSION_NAME=1.0.$GITHUB_RUN_NUMBER" >> $GITHUB_ENV

      - name: Run Lint
        run: ./gradlew lint

      - name: Build with Gradle
        run: ./gradlew build

      - name: Distribut to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: 'testers'
          file: app/build/outputs/apk/staging/debug/app-staging-debug.apk